### ISSUE TITLE
hello! can you share you .tif data?

### ISSUE THREAD

**Issue by sky19941015** [yhpan/GeodetectorPy#1]
i am very happy that your code help me a lot, but i want to learn how to use it , so can you share your .tif data! thank you very much

**Comment by yhpan** [comment]
hello！I have already uploaded the test .tif data on the repository

**Comment by yhpan** [comment]
> i am very happy that your code help me a lot, but i want to learn how to use it , so can you share your .tif data! thank you very much

Hello！I have already uploaded the test .tif data on the repository

**Comment by yhpan** [comment]
Hello！I have already uploaded the test .tif data on the repository
